version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    ignore:
      # protobuf must be handled manually
      - dependency-name: google.golang.org/protobuf
      # K8s dependencies must be handled manually
      - dependency-name: k8s.io/api
        versions:
          - "> 0.17.0"
      - dependency-name: k8s.io/apimachinery
        versions:
          - "> 0.17.0"
      - dependency-name: k8s.io/client-go
        versions:
          - "> 0.17.0"
      - dependency-name: sigs.k8s.io/controller-runtime
        versions:
          - "> 0.3.0"
      # Our own dependencies are handled during releases
      - dependency-name: github.com/submariner-io/*
