---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: monthly
  - package-ecosystem: github-actions
    directory: '/'
    target-branch: "release-0.12"
    schedule:
      interval: monthly
  - package-ecosystem: github-actions
    directory: '/'
    target-branch: "release-0.13"
    schedule:
      interval: monthly
  - package-ecosystem: github-actions
    directory: '/'
    target-branch: "release-0.14"
    schedule:
      interval: monthly
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
    ignore:
      # protobuf must be handled manually
      - dependency-name: google.golang.org/protobuf
      # Our own dependencies are handled during releases
      - dependency-name: github.com/submariner-io/*
