---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
  - package-ecosystem: github-actions
    directory: '/'
    target-branch: "release-0.12"
    schedule:
      interval: daily
  - package-ecosystem: github-actions
    directory: '/'
    target-branch: "release-0.13"
    schedule:
      interval: daily
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    ignore:
      # protobuf must be handled manually
      - dependency-name: google.golang.org/protobuf
      # K8s dependencies must be handled manually
      - dependency-name: k8s.io/*
      - dependency-name: sigs.k8s.io/*
      # Our own dependencies are handled during releases
      - dependency-name: github.com/submariner-io/*
