---
name: End to End Full

on:
  pull_request:
    types: [labeled, opened, synchronize, reopened]

permissions: {}

jobs:
  e2e:
    name: E2E
    if: contains(github.event.pull_request.labels.*.name, 'ready-to-test')
    timeout-minutes: 45
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        deploytool: ['operator']
        external_net: ['']
        globalnet: ['', 'globalnet']
        cable_driver: ['libreswan', 'wireguard', 'vxlan']
        ovn: ['', 'ovn']
        exclude:
          - ovn: 'ovn'
            globalnet: 'globalnet'
          - ovn: 'ovn'
            cable_driver: 'wireguard'
        include:
          - external_net: 'external-net'
          - external_net: 'external-net'
            globalnet: 'globalnet'
    steps:
      - name: Check out the repository
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b

      - name: Run E2E deployment and tests
        if: matrix.external_net != 'external-net'
        uses: submariner-io/shipyard/gh-actions/e2e@devel
        with:
          using: ${{ matrix.cable_driver }} ${{ matrix.deploytool }} ${{ matrix.globalnet }} ${{ matrix.ovn }}

      - name: Run External Network E2E deployment and tests
        if: matrix.external_net == 'external-net'
        uses: submariner-io/shipyard/gh-actions/e2e@devel
        with:
          using: ${{ matrix.external_net }} ${{ matrix.globalnet }}
          skip: ""  # Override skipping external network tests
          plugin: scripts/e2e/external/hook

      - name: Post mortem
        if: failure()
        uses: submariner-io/shipyard/gh-actions/post-mortem@devel
