---
name: End to End Tests

on:
  pull_request:
  push:
    tags:
      - 'v**'

jobs:
  e2e:
    name: E2E
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        deploytool: ['operator', 'helm']
        globalnet: ['', 'globalnet']
        cable_driver: ['', 'wireguard', 'libreswan']
        exclude:
          # Our Helm setup doesnâ€™t know how to deploy other cable drivers
          - deploytool: 'helm'
            cable_driver: 'wireguard'
          - deploytool: 'helm'
            cable_driver: 'libreswan'
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master

      - name: Install WireGuard module (On WireGuard tests)
        if: matrix.cable_driver == 'wireguard'
        run: |
          sudo add-apt-repository -y ppa:wireguard/wireguard # add WireGuard support
          sudo apt update
          sudo apt install -y linux-headers-$(uname -r) wireguard wireguard-dkms
          if [[ "$(uname -r)" =~ -1020- ]]; then
            # the 1020 kernel doesn't have skb_reset_redirect in skbuff.h, patch Wireguard so it doesn't need it
            curl https://git.zx2c4.com/wireguard-linux/patch/drivers/net/wireguard/queueing.h\?id=2c64605b590edadb3fb46d1ec6badb49e940b479 \
              | sudo patch -R /usr/src/wireguard*/queueing.h
            sudo dpkg-reconfigure wireguard-dkms
          fi
          sudo modprobe wireguard

      - name: Reclaim free space!
        run: |
          sudo swapoff -a
          sudo rm -f /swapfile
          df -h
          free -h

      - name: Run E2E deployment and tests
        run: |
          make e2e using="${{ matrix.globalnet }} ${{ matrix.deploytool }} ${{ matrix.cable_driver }}"

      - name: Post Mortem
        if: failure()
        run: |
          df -h
          free -h
          make post-mortem
