on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - 'v**'

name: End to End Tests
jobs:
  e2e:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        globalnet: ['', '--globalnet']
        deploytool: ['operator', 'helm']
        cable_driver: ['', 'wireguard']
        exclude:
          - deploytool: 'helm'
            cable_driver: 'wireguard'
# TODO: Remove exclusion when issue #552 is fixed
          - globalnet: '--globalnet'
            cable_driver: 'wireguard'
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master

      - name: Install WireGuard module (On WireGuard tests)
        if: matrix.cable_driver == 'wireguard'
        run: |
          sudo add-apt-repository -y ppa:wireguard/wireguard # add WireGuard support
          sudo apt-get update
          sudo apt-get install linux-headers-`uname -r` wireguard -y
          sudo modprobe wireguard

      - name: Reclaim free space!
        run: |
          sudo swapoff -a
          sudo rm -f /swapfile
          df -h
          free -h

      - name: Run E2E deployment and tests
        env:
          CLUSTERS_ARGS: ${{ matrix.globalnet }}
          DEPLOY_ARGS: ${{ matrix.globalnet }} --deploytool ${{ matrix.deploytool }}
        run: |
          [[ -z "${{ matrix.cable_driver }}" ]] || DEPLOY_ARGS+=" --deploytool_submariner_args '--cable-driver ${{ matrix.cable_driver }}'"
          make e2e

      - name: Post Mortem
        if: failure()
        run: |
          df -h
          free -h
          make post-mortem
