---
name: Flake Finder

on:
  schedule:
    - cron: "0 0,1 * * *"

permissions: {}

jobs:
  e2e:
    name: E2E
    if: github.repository_owner == 'submariner-io'
    timeout-minutes: 45
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        deploytool: ['operator']
        external_net: ['']
        globalnet: ['', 'globalnet']
        cable_driver: ['libreswan', 'wireguard']
        include:
          - external_net: 'external-net'
          - external_net: 'external-net'
            globalnet: 'globalnet'
    steps:
      - name: Check out the repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

      - name: Run E2E deployment and tests
        if: matrix.external_net != 'external-net'
        uses: submariner-io/shipyard/gh-actions/e2e@devel
        with:
          using: ${{ matrix.cable_driver }} ${{ matrix.deploytool }} ${{ matrix.globalnet }}

      - name: Run External Network E2E deployment and tests
        if: matrix.external_net == 'external-net'
        uses: submariner-io/shipyard/gh-actions/e2e@devel
        with:
          using: ${{ matrix.external_net }} ${{ matrix.globalnet }}
          skip: ""  # Override skipping external network tests

      - name: Post mortem
        if: failure()
        uses: submariner-io/shipyard/gh-actions/post-mortem@devel
