name: Markdown Link Checks
on: pull_request

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    name: Markdown Link Checks
    steps:
    - name: Check out code
      uses: actions/checkout@v1

    - name: Run markdown-link-check
      uses: gaurav-nelson/github-action-markdown-link-check@0.6.0
      with:
        config-file: ".markdownlinkcheck.json"
        check-modified-files-only: "yes"
