name: Markdown Link Checks
on:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  markdown-link-check-periodic:
    runs-on: ubuntu-latest
    name: Markdown Link Checks
    steps:
    - name: Check out code
      uses: actions/checkout@v1

    - name: Run markdown-link-check
      uses: gaurav-nelson/github-action-markdown-link-check@0.6.0
      with:
        config-file: ".markdownlinkcheck.json"

    - name: Raise an Issue to report broken links
      if: ${{ failure() }}
      uses: JasonEtco/create-an-issue@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        filename: .github/ISSUE_TEMPLATE/broken-link.md
