---
name: Multi-arch Builds

on:
  pull_request:

permissions: {}

jobs:
  check-multiarch:
    name: Check the multi-arch builds
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3
      - name: Set up QEMU (to support building on non-native architectures)
        uses: docker/setup-qemu-action@e81a89b1732b9c48d79cd809d8d81d79c4647a18
      - name: Build the multi-arch images
        run: make multiarch-images
      - name: Check that we actually build multi-arch images
        run: bash -c '[ "$(echo package/*.tar)" != "package/*.tar" ]'
