---
name: Multi-arch Builds

on:
  pull_request:

permissions: {}

jobs:
  check-multiarch:
    name: Check the multi-arch builds
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
      - name: Set up QEMU (to support building on non-native architectures)
        uses: docker/setup-qemu-action@2b82ce82d56a2a04d2637cd93a637ae1b359c0a7
      - name: Build the multi-arch images
        run: make multiarch-images
      - name: Check that we actually build multi-arch images
        run: bash -c '[ "$(echo package/*.tar)" != "package/*.tar" ]'
