---
name: Periodic

on:
  schedule:
    - cron: "0 0 * * 0"

permissions: {}

jobs:
  internal-integration:
    name: Internal Integration
    if: github.repository_owner == 'submariner-io'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Check out the repository
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3

      - name: Update internal submariner-io/* dependencies to latest
        run: |
          for dep in $(awk '!/module/ && /github.com.submariner-io/ { print $1 }' go.mod)
            do go get ${dep}@devel
          done

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5b4a9f6a9e2af26e5f02351490b90d01eb8ec1e5
        with:
          title: Update submariner-io/* dependencies to latest
          body: |
            This checks the current status of this repository against the latest version of all the Submariner projects it depends on.
            If something fails, the failure should be investigated and at least tracked as an issue blocking the next release.
            Since some CI only runs periodically, if on-PR CI passes it's still good to merge this update for full integration coverage.
          commit-message: |
            Update submariner-io/* dependencies to latest

            This upgrades all our dependencies on other Submariner projects to their
            latest development snapshots, ensuring the code in the projects remains
            coherent and that tests of development images verify the latest code.
          signoff: true
          author: GitHub <noreply@github.com>
          labels: automated, dependencies

  markdown-link-check-periodic:
    name: Markdown Links (all files)
    if: github.repository_owner == 'submariner-io'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Check out the repository
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3

      - name: Run markdown-link-check
        uses: gaurav-nelson/github-action-markdown-link-check@d53a906aa6b22b8979d33bc86170567e619495ec
        with:
          config-file: ".markdownlinkcheck.json"

      - name: Raise an Issue to report broken links
        if: ${{ failure() }}
        uses: peter-evans/create-issue-from-file@433e51abf769039ee20ba1293a088ca19d573b7f
        with:
          title: Broken link detected by periodic linting
          content-filepath: .github/ISSUE_TEMPLATE/broken-link.md
          labels: automated, broken link
