---
name: Upgrade

on:
  pull_request:
    branches: [devel]

permissions: {}

jobs:
  upgrade-e2e:
    name: Latest Release to Latest Version
    timeout-minutes: 45
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Check out the repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9

      - name: Install an old cluster, upgrade it and check it
        uses: submariner-io/shipyard/gh-actions/upgrade-e2e@devel

      - name: Post Mortem
        if: failure()
        uses: submariner-io/shipyard/gh-actions/post-mortem@devel
