---
name: Upgrade

on:
  pull_request:

jobs:
  upgrade-e2e:
    name: Latest Release to Latest Version
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@master

      - name: Reclaim free space!
        run: |
          sudo swapoff -a
          sudo rm -f /swapfile
          df -h
          free -h

      - name: Install an old cluster, upgrade it and check it
        run: |
          make upgrade-e2e

      - name: Post Mortem
        if: failure()
        run: |
          df -h
          free -h
          make post-mortem
