---
name: Upgrade

on:
  pull_request:
    branches: [release-0.14]

permissions: {}

jobs:
  upgrade-e2e:
    name: Latest Release to Latest Version
    timeout-minutes: 45
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Check out the repository
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b

      - name: Install an old cluster, upgrade it and check it
        uses: submariner-io/shipyard/gh-actions/upgrade-e2e@release-0.14

      - name: Post Mortem
        if: failure()
        uses: submariner-io/shipyard/gh-actions/post-mortem@release-0.14
